# Generated by Django 2.2.4 on 2019-08-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_auto_20190814_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_number',
        ),
    ]
