# Generated by Django 2.2.4 on 2019-08-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_auto_20190815_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='type',
            new_name='menu_type',
        ),
    ]
