# Generated by Django 2.2.4 on 2019-08-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0005_auto_20190815_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='tickets',
        ),
    ]
