# Generated by Django 2.2.4 on 2019-08-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0006_remove_menu_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='tickets',
            field=models.ManyToManyField(related_name='menu_items', to='pos_app.Ticket'),
        ),
    ]
