# Generated by Django 2.2.4 on 2019-08-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0007_menu_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='tickets',
        ),
        migrations.AddField(
            model_name='ticket',
            name='menu_items',
            field=models.ManyToManyField(related_name='tickets', to='pos_app.Menu'),
        ),
    ]
