# Generated by Django 2.2.4 on 2019-08-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0009_auto_20190815_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='table_number',
            field=models.CharField(default='', max_length=128),
        ),
    ]
