# Generated by Django 2.2.4 on 2019-08-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0010_ticket_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='table_number',
            field=models.CharField(default='number not provided', max_length=128),
        ),
    ]
