# Generated by Django 2.2.4 on 2019-08-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0012_auto_20190816_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
