# Generated by Django 2.2.4 on 2019-08-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0014_auto_20190820_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='total',
        ),
        migrations.AddField(
            model_name='menu',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
